version: '3.3'
services:
  httpd:
    image: nginx:latest
    restart: always
    volumes:
      - './html:/usr/share/nginx/html'
    ports:
      - '8080:80'
    networks:
      - bulma_practice_net
networks:
  bulma_practice_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
